const state = {
  sessions:{
    access_token:window.localStorage.getItem('TOKEN'),
    user:{}
  },
  templateSettings:{
    drawer:false
  },
  notification:{
    type: null,
    text: null
  },
  pageController:{},
  clients:[],
  discounts:[],
  cards:[],
  users:[],
  roles:[],
  reports:[],
  reportsShare:[],
  divisions:[],
  companies:[],
  shops:[],
  shopGrades:[],
  shopShifts:[],
  shopShiftsPaginate: [],
  shopTypes:[],
  shifts:[],
  cities:[],
  regions:[],
  staffPlans:[],
  staffPlansPaginate:[],
  products:[],
  productTypes:[],
  productBrands:[],
  productGroups:[],
  productRemains:[],
  measureTypes:[],
  productGroupPlans:[],
  productGroupPlanTypes:[],
  visitLogs:[],
  operations:[],
  warehouses:[],
  warehouseTypes:[],
  coeffs:[],
  coeffTypes:[],
  checkDetails:[],
  checkHeaders:[],
  checkHeader:{},
  checkTypes:[],
  checkOperations:[],
  cashDescs:[],
  fileLogs:[],
  fileTypes:[],
  divisionMonthReports:[],
  divisionPieMonthReports:[],
};
export default state;
